apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ms-srt-wallet.fullname" . }}
  labels:
    {{- include "ms-srt-wallet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ms-srt-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ms-srt-wallet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ms-srt-wallet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_HOST
              value: {{ .Values.MYSQL_HOST | quote }}
            - name: MYSQL_USER
              value: {{ .Values.MYSQL_USER | quote }}
            - name : MYSQL_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.MYSQLSecretName | quote }}
                  key: {{ .Values.MYSQLSecretKey | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.MYSQL_DATABASE | quote }}

            - name: NODE_ENV
              value: {{ .Values.NodeEnvValue | quote }}

            - name : ETHSCAN_APIKEY
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.ETHAPIKEYName | quote }}
                  key: {{ .Values.ETHAPIKEYValue | quote }}

            - name : ALCHEMY_APIKEY
              valueFrom:
                secretKeyRef: 
                  name: {{ .Values.ALCHEMY_APIKEYName | quote }}
                  key: {{ .Values.ALCHEMY_APIKEYSValue | quote }}
          ports:
            - name: http
              containerPort: 5502
              protocol: TCP
            - name: socket
              containerPort: 5702
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
